# Runs test related tasks.

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Nextflow
      run: |
        # Install latest version of Nextflow
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/bin
    - name: Regression tests
      run: ./regression_tests.sh -s
      shell: bash
